plugins {
    id 'java-library'
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.ai:spring-ai-bom:2.0.0'
    }
}

dependencies {
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    implementation 'org.springframework.modulith:spring-modulith-api'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}